name: Build
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - run: cargo fmt --all --check

  build-desktop:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt-get install -y libsdl2-dev libsdl2-image-dev
      - name: Cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - run: cargo build --release

  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - run: sudo apt-get install -y binaryen
      - name: Cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - run: cargo install wasm-bindgen-cli
      - run: ./build.sh

      - name: Checkout GH pages repo
        if: github.ref == 'refs/heads/master'
        uses: actions/checkout@v2
        with:
          repository: suomipelit/utk-level-editor-web
          path: deploy
          token: ${{secrets.DEPLOY_TOKEN}}

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          cp -r dist/* ../deploy/
          cd ../deploy
          git config --global user.email "GitHub Actions"
          git config --global user.name "actions@github.com"
          if ! git diff --exit-code; then
            git commit -am "Deploy commit ${{github.sha}} of ${{github.repository}}"
            git push
          fi
