[package]
name = "utk-level-editor-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
console_log = "0.2.0"
log = "0.4.17"
wasm-bindgen = "0.2.83"
